language: node_js
node_js:
  - "node"
cache:
  yarn: true
  directories:
    - "node_modules"
script: yarn build
before_deploy: npm -g install now --no-save
deploy:
  - provider: script
    script: now --public --token $NOW_TOKEN ./build
    skip_cleanup: true
    on:
      all_branches: true