language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
script: npm run build
before_deploy: npm -g install now --no-save
deploy:
  - provider: script
    script: now --public --token $NOW_TOKEN ./build && now alias --token $NOW_TOKEN
    skip_cleanup: true
    on:
      all_branches: true