language: node_js
node_js:
  - "node"
cache:
  yarn: true
  directories:
    - "node_modules"
before_deploy: yarn add now
deploy:
  - provider: script
    script: now --public --token $NOW_TOKEN && now alias --token $NOW_TOKEN
    skip_cleanup: true
    on:
      all_branches: true