language: node_js
node_js:
  - "node"
branches:
  only:
    - master
    - /^feat\/.*$/
cache:
  yarn: true
  directories:
    - "node_modules"
script: yarn build
before_deploy: npm -g install now
deploy:
  - provider: script
    script: >
      now --public --name twitter-demo-frontend --token $NOW_TOKEN ./build &&
      now alias twitter-demo-frontend-scrat98.now.sh --token $NOW_TOKEN
    skip_cleanup: true
    on: master
  - provider: script
    script:
      - export FEAT_NAME="${TRAVIS_BRANCH//\//-}"
      - echo $FEAT_NAME
      - now --public --name twitter-demo-frontend --token $NOW_TOKEN ./build && now alias twitter-demo-frontend-scrat98-$FEAT_NAME.now.sh --token $NOW_TOKEN
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^feat\/.*$