language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
script: yarn build
before_deploy: npm -g install now --no-save
deploy:
  - provider: script
    script: now --token $NOW_TOKEN --public && now alias --token $NOW_TOKEN --public
    skip_cleanup: true
    on:
      all_branches: true